name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run install
        run: ./gradlew install

      - name: Run check
        run: ./gradlew check

      - name: Deploy docs
        env:
          githubToken: ${{ secrets.GITHUBTOKEN }}
        if: ${{ github.event_name == 'push' && contains(github.ref, "master") }}
        run: ./scripts/deploy_docs.sh